spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/car
    username: root
    password: root
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379