name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-agenda:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: cd android-sua-primeira-app-mobile/agenda && chmod +x gradlew
    - name: Build with Gradle
      run: cd android-sua-primeira-app-mobile/agenda && ./gradlew assembleRelease --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: agenda-apk
        path: android-sua-primeira-app-mobile/agenda/app/build/outputs/apk/release/*.apk

  build-agenda-v2:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: cd android-avancando-listeners-menu-ui/agenda && chmod +x gradlew
    - name: Build with Gradle
      run: cd android-avancando-listeners-menu-ui/agenda && ./gradlew assembleRelease --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: agenda-v2-apk
        path: android-avancando-listeners-menu-ui/agenda/app/build/outputs/apk/release/*.apk

  build-agenda-v3:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: cd android-refinando-o-projeto/agenda && chmod +x gradlew
    - name: Build with Gradle
      run: cd android-refinando-o-projeto/agenda && ./gradlew assembleRelease --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: agenda-v3-apk
        path: android-refinando-o-projeto/agenda/app/build/outputs/apk/release/*.apk        