name: Docker Images CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build the car-service Docker image
      run: |
        docker build -t car-service:latest backend/jvm/kotlin/kotlin-aplicacoes-resilientes-assincronas/car-service